# Generated by Django 5.0.1 on 2024-01-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.CharField(default=3, max_length=100),
        ),
    ]
