# Generated by Django 5.0.1 on 2024-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_passenger_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='age',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
