# Generated by Django 5.0.1 on 2024-01-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_passenger_age_alter_passenger_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
