# Generated by Django 5.0.1 on 2024-01-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_passenger_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
