# Generated by Django 5.0.1 on 2024-01-11 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='passenger',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
