# Generated by Django 5.0.1 on 2024-01-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('train_name', models.CharField(max_length=100, unique=True)),
                ('from_station', models.CharField(max_length=50)),
                ('to_station', models.CharField(max_length=50)),
                ('total_seats_1ac', models.IntegerField(default=30)),
                ('total_seats_2ac', models.IntegerField(default=30)),
                ('total_seats_3ac', models.IntegerField(default=30)),
                ('fare_1ac', models.IntegerField(default=50)),
                ('fare_2ac', models.IntegerField(default=100)),
                ('fare_3ac', models.IntegerField(default=200)),
                ('runs_on', models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=14, null=True)),
            ],
        ),
    ]
