# Generated by Django 5.0.1 on 2024-01-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='from_station',
            new_name='from_station_code',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='to_station',
            new_name='to_station_code',
        ),
        migrations.AddField(
            model_name='train',
            name='train_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='runs_on',
            field=models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], default='M', max_length=14, null=True),
        ),
    ]
