# Generated by Django 5.0.1 on 2024-01-04 18:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_train_runs_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='runs_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2), blank=True, default=list, null=True, size=None),
        ),
    ]
