# Generated by Django 5.0.1 on 2024-01-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_train_runs_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='runs_on',
            field=models.CharField(max_length=20),
        ),
    ]
