# Generated by Django 5.0.1 on 2024-01-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='departure_time',
        ),
    ]
