# Generated by Django 5.0.1 on 2024-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_station_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='train_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
