# Generated by Django 5.0.1 on 2024-01-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_station_train_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='halt_time',
            field=models.CharField(max_length=10),
        ),
    ]
